version: "3.8"

services:
  app:
    container_name: wa_frontend_dev
    image: wa_frontend_dev
    build:
      context: .
      target: development
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./src:/frontend/app
      - /frontend/app/node_modules/
    ports:
      - 3000:3000