version: '3.8'

services:
  backend:
    container_name: wa_backend_prod
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: production
    command: npm run start
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://user:password@postgres:5432/db
    ports:
      - '5000:5000'

  frontend:
    container_name: wa_frontend_prod
    image: wa_frontend_prod
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: production
    ports:
      - 8081:80
    links:
      - backend

  postgres:
    container_name: wa_postgres_prod
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    container_name: wa_postgres_admin_prod
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
